POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "marysue",
    "name": "Mary Sue",
    "password": "securepassword123"
}
###
GET http://localhost:3001/api/users
###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Tracy Anderson",
    "number": "345-67891011",
    "userId": "69bb37463b4c4dc5e349924f"
}